import { readFile } from 'node:fs/promises'
import { join } from 'node:path'

/*
 * The theme, assembled into one stylesheet.
 *
 * src/styles/ holds six files that are composed rather than linked: Typora's base, its
 * CodeMirror styles, the shared structure (kiwi), the glass material (glassy), and the two
 * palettes. They are written as separate files because they change for different reasons —
 * structure rarely, material occasionally, palettes whenever a colour feels wrong — and
 * concatenated here because the browser has no reason to know that.
 *
 * Doing it at build time rather than with runtime `@import` is what avoids a flash: an
 * `@import` is render-blocking *and* serialised, so a palette pulled in that way arrives a
 * full round trip after the page. Here both palettes ship in one file scoped by
 * [data-theme], so switching light to dark is an attribute flip with nothing to fetch.
 *
 * Concatenating is only safe while none of the six contains `url()` — a relative reference
 * would resolve against dist/theme.css instead of src/styles/ and quietly 404. That is
 * asserted below rather than remembered.
 */

const LAYERS = '@layer typora-base, typora-theme, typora-bridge, app;'

interface Palette {
  name: string
  vars: string
}

/**
 * Pull the declarations out of a palette's single top-level `:root { … }` block.
 *
 * A palette is variables and nothing else, which is what lets the same declarations be
 * emitted three times below under different selectors. Both checks below exist so that
 * adding a rule to a palette fails the build with an explanation, rather than having the
 * rule silently dropped or duplicated into all three scopes.
 */
function extractRoot(css: string, file: string): string {
  const blocks = [...css.matchAll(/^:root\s*\{$/gm)]
  if (blocks.length !== 1) {
    throw new Error(
      `${file}: expected exactly one top-level :root block, found ${blocks.length}. ` +
        `A palette must be variables only — put anything else in kiwi.css or glassy.css.`
    )
  }
  const start = blocks[0]!.index! + blocks[0]![0].length
  const end = css.indexOf('\n}', start)
  if (end === -1) throw new Error(`${file}: unterminated :root block`)

  const rest = css.slice(end + 2)
  if (rest.trim()) {
    throw new Error(
      `${file}: unexpected rules after the :root block. A palette is variables only; ` +
        `anything here would be dropped. Put it in kiwi.css or glassy.css instead.`
    )
  }
  return css.slice(start, end)
}

async function read(dir: string, name: string): Promise<string> {
  const css = await readFile(join(dir, name), 'utf8')

  // Comments are stripped before the check, not after: these files are heavily commented,
  // and prose that merely *mentions* a url() reference is not a url() reference. Testing the
  // raw text instead makes the guard fire on its own documentation.
  const rules = css.replace(/\/\*[\s\S]*?\*\//g, '')
  if (/url\(/.test(rules)) {
    throw new Error(
      `${name}: contains url(), which concatenation would break — the reference would ` +
        `resolve against dist/theme.css instead of src/styles/. Either serve this file ` +
        `separately from public/, or rewrite its URLs in src/site/theme.ts.`
    )
  }
  return css
}

/**
 * Build the single stylesheet every page links.
 *
 * Cascade order is declared once, up front: Typora's base, then the theme, then our
 * corrections, then our chrome. Our own layers are declared by src/shell/*.css, which loads
 * after this file — layer order is fixed by first appearance, so it is established here and
 * the shell only ever fills its slot.
 */
export async function buildTheme(root: string): Promise<string> {
  // Build inputs, not served assets: they end up inside dist/theme.css, so keeping them out
  // of public/ avoids shipping a second copy of the same 690 KB that nothing ever requests.
  const styles = join(root, 'src/styles')

  const [baseCss, codemirrorCss, kiwi, glassy, su, qi] = await Promise.all([
    read(styles, 'base.css'),
    read(styles, 'codemirror.css'),
    read(styles, 'kiwi.css'),
    read(styles, 'glassy.css'),
    read(styles, 'glassy-su.css'),
    read(styles, 'glassy-qi.css'),
  ])

  const palettes: Palette[] = [
    { name: 'light', vars: extractRoot(su, 'glassy-su.css') },
    { name: 'dark', vars: extractRoot(qi, 'glassy-qi.css') },
  ]
  const [light, dark] = palettes as [Palette, Palette]

  return `/* Generated by src/site/theme.ts from src/styles/ — do not edit. */
${LAYERS}

@layer typora-base.core {
${baseCss}
${codemirrorCss}
}

@layer typora-theme {
${kiwi}
${glassy}

/* ── Palettes ─────────────────────────────────────────────────────────────────────────
 *
 * Su and Qi, scoped so both ship in one file and the toggle is an attribute flip.
 *
 * The bare :root is the no-JavaScript default, and the media query below it is what makes
 * that default follow the reader's system preference when nothing has set [data-theme].
 * The explicit dark rule comes last so it outranks the media query at equal specificity —
 * a reader who has chosen light keeps light on a machine set to dark.
 */
:root,
:root[data-theme='light'] {
${light.vars}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${dark.vars}
  }
}

:root[data-theme='dark'] {
${dark.vars}
}
}
`
}
